/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;

	public class LoadingUI extends View {
		public var bars:Image;
		public var btn_start:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":1282,"height":709},"compId":1,"child":[{"type":"Image","props":{"y":0,"x":0,"skin":"fish/img/img4.jpg"},"compId":2},{"type":"Image","props":{"y":0,"x":0,"skin":"fish/img/img3.png"},"compId":3},{"type":"Box","props":{"y":409,"x":428},"compId":13,"child":[{"type":"Image","props":{"skin":"fish/load/linebg.png"},"compId":11},{"type":"Image","props":{"y":36,"x":32,"var":"bars","skin":"fish/load/bars.png","sizeGrid":"0,11,0,10","scaleY":0.4},"compId":12},{"type":"Button","props":{"y":156,"x":84,"width":256,"var":"btn_start","skin":"fish/load/button_star.png","height":77},"compId":14}]}],"loadList":["fish/img/img4.jpg","fish/img/img3.png","fish/load/linebg.png","fish/load/bars.png","fish/load/button_star.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}